#include "pch.h"
#include "App.xaml.h"
#include "MainWindow.xaml.h"

// The entry point (wWinMain) is generated by the XAML compiler (#428).

namespace winrt::Rhythm::implementation {

App::App() = default;

void App::OnLaunched(winrt::Microsoft::UI::Xaml::LaunchActivatedEventArgs const&) {
    window_ = make<MainWindow>();
    window_.Activate();
}

} // namespace winrt::Rhythm::implementation
